package Windows;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Links.ConectionSQL;
/**
 *
 * @author AA2020
 */
public class NeveriaFinalView extends javax.swing.JFrame {
    ConectionSQL connectObjSQL;
    DefaultTableModel tableModel;
    DefaultTableModel secondTableModel;

    /**
     * Creates new form NeveriaFinalView
     */
    public NeveriaFinalView() {
        //this.setLocationRelativeTo(null);
        initComponents();
        connectObjSQL = new ConectionSQL();
        connectObjSQL.ConnectDataBase();
        UpdateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedAll = new javax.swing.JTabbedPane();
        jPanTipoHelado = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        lblLaNeveria = new javax.swing.JLabel();
        lblDESCRIPCION3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblREGISTRARNUEVOTIPOHELADO = new javax.swing.JLabel();
        lblTIPOHELADO = new javax.swing.JLabel();
        txtTipoHelado = new javax.swing.JTextField();
        lblDESCRIPCION = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTipoHelado = new javax.swing.JTable();
        jSpiDeslizarUNO = new javax.swing.JSpinner();
        lblDESCRIPCION1 = new javax.swing.JLabel();
        jPanNuevoProducto = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblLOGO = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        lblLANEVERIA = new javax.swing.JLabel();
        lblDESCRIPCION4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblREGISTRARNUEVOPRODUCTO = new javax.swing.JLabel();
        lblPRODUCTO = new javax.swing.JLabel();
        lblPRECIO = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        lblSTOCK = new javax.swing.JLabel();
        lblDESCRIP = new javax.swing.JLabel();
        txtDescrip = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProducto = new javax.swing.JTable();
        lblDESCRIPCION2 = new javax.swing.JLabel();
        jSpiDeslizarDOS = new javax.swing.JSpinner();
        txtPrecio = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("La Nevería ®");
        setLocation(new java.awt.Point(250, 25));

        jTabbedAll.setBackground(new java.awt.Color(204, 0, 0));
        jTabbedAll.setForeground(new java.awt.Color(255, 204, 0));
        jTabbedAll.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        jTabbedAll.setFont(new java.awt.Font("Forte", 1, 18)); // NOI18N

        jPanTipoHelado.setBackground(java.awt.Color.yellow);

        jPanel5.setBackground(new java.awt.Color(204, 0, 0));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/neveria.png"))); // NOI18N

        btnSalir.setBackground(new java.awt.Color(153, 0, 0));
        btnSalir.setFont(new java.awt.Font("Forte", 1, 48)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 153, 0));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cerrar-sesion.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblLaNeveria.setFont(new java.awt.Font("Forte", 3, 48)); // NOI18N
        lblLaNeveria.setForeground(java.awt.Color.yellow);
        lblLaNeveria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLaNeveria.setText("La Nevería ®");

        lblDESCRIPCION3.setFont(new java.awt.Font("Forte", 0, 14)); // NOI18N
        lblDESCRIPCION3.setForeground(new java.awt.Color(238, 187, 0));
        lblDESCRIPCION3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDESCRIPCION3.setText("© Adrián Alfonzo 2020 | MEED | UNICAES");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLaNeveria, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                    .addComponent(lblDESCRIPCION3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lblLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLaNeveria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(120, 120, 120)
                .addComponent(lblDESCRIPCION3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(153, 0, 0));

        lblREGISTRARNUEVOTIPOHELADO.setFont(new java.awt.Font("Forte", 1, 36)); // NOI18N
        lblREGISTRARNUEVOTIPOHELADO.setForeground(new java.awt.Color(255, 204, 0));
        lblREGISTRARNUEVOTIPOHELADO.setText("Registrar nuevo tipo de helado");

        lblTIPOHELADO.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        lblTIPOHELADO.setForeground(new java.awt.Color(238, 187, 0));
        lblTIPOHELADO.setText("Tipo de helado:");

        txtTipoHelado.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N

        lblDESCRIPCION.setFont(new java.awt.Font("Forte", 1, 14)); // NOI18N
        lblDESCRIPCION.setForeground(new java.awt.Color(238, 187, 0));
        lblDESCRIPCION.setText("Desliza para eliminar");

        txtDescripcion.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        txtDescripcion.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnRegistrar.setBackground(new java.awt.Color(153, 0, 0));
        btnRegistrar.setFont(new java.awt.Font("Forte", 1, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 153, 0));
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/registro.png"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(153, 0, 0));
        btnActualizar.setFont(new java.awt.Font("Forte", 1, 18)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 153, 0));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/actualizar.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnBorrar.setBackground(new java.awt.Color(153, 0, 0));
        btnBorrar.setFont(new java.awt.Font("Forte", 1, 18)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(255, 153, 0));
        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/basura.png"))); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        jTableTipoHelado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TIPO HELADO", "DESCRIPCIÓN"
            }
        ));
        jTableTipoHelado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTipoHeladoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTipoHelado);

        jSpiDeslizarUNO.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        jSpiDeslizarUNO.setModel(new javax.swing.SpinnerNumberModel(1, 1, 1000, 1));

        lblDESCRIPCION1.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        lblDESCRIPCION1.setForeground(new java.awt.Color(238, 187, 0));
        lblDESCRIPCION1.setText("Descripción:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblDESCRIPCION)
                                .addComponent(lblTIPOHELADO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSpiDeslizarUNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblDESCRIPCION1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDescripcion)
                            .addComponent(txtTipoHelado))
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblREGISTRARNUEVOTIPOHELADO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblREGISTRARNUEVOTIPOHELADO, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTIPOHELADO, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(txtTipoHelado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblDESCRIPCION1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDESCRIPCION)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpiDeslizarUNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnActualizar)
                    .addComponent(btnBorrar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanTipoHeladoLayout = new javax.swing.GroupLayout(jPanTipoHelado);
        jPanTipoHelado.setLayout(jPanTipoHeladoLayout);
        jPanTipoHeladoLayout.setHorizontalGroup(
            jPanTipoHeladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanTipoHeladoLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanTipoHeladoLayout.setVerticalGroup(
            jPanTipoHeladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedAll.addTab("Tipo de Helado", jPanTipoHelado);

        jPanNuevoProducto.setBackground(java.awt.Color.yellow);

        jPanel3.setBackground(new java.awt.Color(204, 0, 0));

        lblLOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/neveria.png"))); // NOI18N

        btnExit.setBackground(new java.awt.Color(153, 0, 0));
        btnExit.setFont(new java.awt.Font("Forte", 1, 48)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 153, 0));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cerrar-sesion.png"))); // NOI18N
        btnExit.setText("Salir");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblLANEVERIA.setFont(new java.awt.Font("Forte", 3, 48)); // NOI18N
        lblLANEVERIA.setForeground(java.awt.Color.yellow);
        lblLANEVERIA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLANEVERIA.setText("La Nevería ®");

        lblDESCRIPCION4.setFont(new java.awt.Font("Forte", 0, 14)); // NOI18N
        lblDESCRIPCION4.setForeground(new java.awt.Color(238, 187, 0));
        lblDESCRIPCION4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDESCRIPCION4.setText("© Adrián Alfonzo 2020 | MEED | UNICAES");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lblLOGO)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLANEVERIA, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                    .addComponent(lblDESCRIPCION4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLOGO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLANEVERIA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(120, 120, 120)
                .addComponent(lblDESCRIPCION4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(153, 0, 0));

        lblREGISTRARNUEVOPRODUCTO.setFont(new java.awt.Font("Forte", 1, 36)); // NOI18N
        lblREGISTRARNUEVOPRODUCTO.setForeground(new java.awt.Color(255, 204, 0));
        lblREGISTRARNUEVOPRODUCTO.setText("Registrar nuevo producto");

        lblPRODUCTO.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        lblPRODUCTO.setForeground(new java.awt.Color(238, 187, 0));
        lblPRODUCTO.setText("Producto:");

        lblPRECIO.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        lblPRECIO.setForeground(new java.awt.Color(238, 187, 0));
        lblPRECIO.setText("Precio: $");

        txtProducto.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N

        lblSTOCK.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        lblSTOCK.setForeground(new java.awt.Color(238, 187, 0));
        lblSTOCK.setText("Stock:");

        lblDESCRIP.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        lblDESCRIP.setForeground(new java.awt.Color(238, 187, 0));
        lblDESCRIP.setText("Descripción:");

        txtDescrip.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N

        btnRegister.setBackground(new java.awt.Color(153, 0, 0));
        btnRegister.setFont(new java.awt.Font("Forte", 1, 18)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 153, 0));
        btnRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/registro.png"))); // NOI18N
        btnRegister.setText("Registrar");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(153, 0, 0));
        btnUpdate.setFont(new java.awt.Font("Forte", 1, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 153, 0));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/actualizar.png"))); // NOI18N
        btnUpdate.setText("Actualizar");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(153, 0, 0));
        btnDelete.setFont(new java.awt.Font("Forte", 1, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 153, 0));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/basura.png"))); // NOI18N
        btnDelete.setText("Borrar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jTableProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PRODUCTO", "PRECIO", "STOCK", "DESCRIPCIÓN"
            }
        ));
        jTableProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProductoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableProducto);

        lblDESCRIPCION2.setFont(new java.awt.Font("Forte", 1, 14)); // NOI18N
        lblDESCRIPCION2.setForeground(new java.awt.Color(238, 187, 0));
        lblDESCRIPCION2.setText("Desliza para eliminar");

        jSpiDeslizarDOS.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        jSpiDeslizarDOS.setModel(new javax.swing.SpinnerNumberModel(1, 1, 1000, 1));

        txtPrecio.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N

        txtStock.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblREGISTRARNUEVOPRODUCTO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblDESCRIP)
                                            .addComponent(lblPRECIO)
                                            .addComponent(lblPRODUCTO)
                                            .addComponent(lblDESCRIPCION2)
                                            .addComponent(jSpiDeslizarDOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(lblSTOCK)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 11, Short.MAX_VALUE)))
                        .addGap(40, 40, 40))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblREGISTRARNUEVOPRODUCTO, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPRODUCTO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPRECIO, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSTOCK, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblDESCRIP, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDESCRIPCION2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpiDeslizarDOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegister)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDelete)
                        .addComponent(btnUpdate)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanNuevoProductoLayout = new javax.swing.GroupLayout(jPanNuevoProducto);
        jPanNuevoProducto.setLayout(jPanNuevoProductoLayout);
        jPanNuevoProductoLayout.setHorizontalGroup(
            jPanNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanNuevoProductoLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanNuevoProductoLayout.setVerticalGroup(
            jPanNuevoProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedAll.addTab("Productos (Helados)", jPanNuevoProducto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedAll)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedAll)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void UpdateTable(){
        connectObjSQL.UpdateHeladosType(tableModel, jTableTipoHelado);
        connectObjSQL.UpdateHeladosType(tableModel, jTableTipoHelado);
        connectObjSQL.UpdateHeladosType(tableModel, jTableTipoHelado);
        connectObjSQL.UpdateHeladosType(tableModel, jTableTipoHelado);
        
        connectObjSQL.UpdateProducto(tableModel, jTableProducto);
        connectObjSQL.UpdateProducto(tableModel, jTableProducto);
        connectObjSQL.UpdateProducto(tableModel, jTableProducto);
        connectObjSQL.UpdateProducto(tableModel, jTableProducto);
        connectObjSQL.UpdateProducto(tableModel, jTableProducto);
        connectObjSQL.UpdateProducto(tableModel, jTableProducto);
    }
    
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        connectObjSQL.InsertarTipoHelado(this.txtTipoHelado.getText(), this.txtDescripcion.getText());
        this.UpdateTable();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        try {
            int Indice= jTableTipoHelado.getSelectedRow();
            DefaultTableModel mdlTmp=(DefaultTableModel)jTableTipoHelado.getModel();
            connectObjSQL.ActualizarTipoHelado(jTableTipoHelado, this.txtTipoHelado.getText(), this.txtDescripcion.getText(), Integer.parseInt(mdlTmp.getValueAt(Indice, 0).toString()));
            this.UpdateTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar precisamente algún CAMPO en la TABLA");
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        connectObjSQL.EliminarTipoHelado((Integer)this.jSpiDeslizarUNO.getValue());
        this.UpdateTable();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        connectObjSQL.InsertarProducto(this.txtProducto.getText(), Double.parseDouble(this.txtPrecio.getText()), Integer.parseInt(this.txtStock.getText()), txtDescrip.getText());
        this.UpdateTable();
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            int Indice= jTableProducto.getSelectedRow();
            DefaultTableModel mdlTmp=(DefaultTableModel)jTableProducto.getModel();
            connectObjSQL.ActualizarProducto(jTableProducto, this.txtProducto.getText(), Double.parseDouble(this.txtPrecio.getText()), Integer.parseInt(this.txtStock.getText()), txtDescrip.getText(), Integer.parseInt(mdlTmp.getValueAt(Indice, 0).toString()));
            this.UpdateTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar precisamente algún CAMPO en la TABLA");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        connectObjSQL.EliminarProducto((Integer)this.jSpiDeslizarDOS.getValue());
        this.UpdateTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jTableProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductoMouseClicked
        int Indice = this.jTableProducto.getSelectedRow();
        DefaultTableModel mdlTmp = (DefaultTableModel) this.jTableProducto.getModel();

        txtProducto.setText(mdlTmp.getValueAt(Indice, 1).toString().trim());
        txtPrecio.setText(mdlTmp.getValueAt(Indice, 2).toString().trim());
        txtStock.setText(mdlTmp.getValueAt(Indice, 3).toString().trim());
        txtDescrip.setText(mdlTmp.getValueAt(Indice, 4).toString().trim());
    }//GEN-LAST:event_jTableProductoMouseClicked

    private void jTableTipoHeladoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTipoHeladoMouseClicked
        int Indice = this.jTableTipoHelado.getSelectedRow();
        DefaultTableModel mdlTmp = (DefaultTableModel) this.jTableTipoHelado.getModel();

        txtTipoHelado.setText(mdlTmp.getValueAt(Indice, 1).toString().trim());
        txtDescripcion.setText(mdlTmp.getValueAt(Indice, 2).toString().trim());
    }//GEN-LAST:event_jTableTipoHeladoMouseClicked

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NeveriaFinalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NeveriaFinalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NeveriaFinalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NeveriaFinalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NeveriaFinalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel jPanNuevoProducto;
    private javax.swing.JPanel jPanTipoHelado;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpiDeslizarDOS;
    private javax.swing.JSpinner jSpiDeslizarUNO;
    private javax.swing.JTabbedPane jTabbedAll;
    private javax.swing.JTable jTableProducto;
    private javax.swing.JTable jTableTipoHelado;
    private javax.swing.JLabel lblDESCRIP;
    private javax.swing.JLabel lblDESCRIPCION;
    private javax.swing.JLabel lblDESCRIPCION1;
    private javax.swing.JLabel lblDESCRIPCION2;
    private javax.swing.JLabel lblDESCRIPCION3;
    private javax.swing.JLabel lblDESCRIPCION4;
    private javax.swing.JLabel lblLANEVERIA;
    private javax.swing.JLabel lblLOGO;
    private javax.swing.JLabel lblLaNeveria;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPRECIO;
    private javax.swing.JLabel lblPRODUCTO;
    private javax.swing.JLabel lblREGISTRARNUEVOPRODUCTO;
    private javax.swing.JLabel lblREGISTRARNUEVOTIPOHELADO;
    private javax.swing.JLabel lblSTOCK;
    private javax.swing.JLabel lblTIPOHELADO;
    private javax.swing.JTextField txtDescrip;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtTipoHelado;
    // End of variables declaration//GEN-END:variables
}
